=== alebagnato/FITTEST/ITE Release/eu.fittest.fbk/eu.fittest.xinputminer/src/main/xsd/itelog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">

	<xs:element name="body">
		<xs:complexType>
			<xs:sequence>
				<!--  High Level Only -->
				<xs:element name="E" type="EType" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="EType">
		<xs:choice>
			<xs:element name="O" type="OType" maxOccurs="unbounded" />
			<xs:element name="V" type="VType" maxOccurs="unbounded"
				nillable="true" />
		</xs:choice>
		<xs:attribute name="t" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="OType">
		<xs:sequence>
			<xs:element name="fd" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:choice>
						<xs:element name="O" type="OType" />
						<xs:element name="V" type="VType" />
					</xs:choice>	
					<xs:attribute name="n" type="xs:string" />	
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="ty" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="VType">
		<xs:attribute name="ty" type="xs:string" />
		<xs:attribute name="v" type="xs:string" />
	</xs:complexType>

</xs:schema>

=== alebagnato/FITTEST/ITE Components standalone/transformtools/eu.fittest.xinputminer/src/main/xsd/itelog.xml
<?xml version="1.0" encoding="UTF-8"?>
<body xmlns="http://www.fittest.eu/itelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fittest.eu/itelog itelog.xsd ">
	<E>
		<O ty="Struct">
			<fd n="action">
				<V ty="string" v="open"></V>
			</fd>
			<fd n="parameters">
				<O ty="Array">
					<fd n="url">
						<V ty="url" v="/~guitest/CuteNews/index.php"></V>
					</fd>
				</O>
			</fd>
		</O>
		<O ty="Struct">
			<fd n="action">
				<V ty="string" v="open"></V>
			</fd>
			<fd n="parameters">
				<O ty="Array">
					<fd n="url">
						<V ty="url" v="/~guitest/CuteNews/index.php"></V>
					</fd>
				</O>
			</fd>
		</O>
	</E>
	<E>
		<O ty="Struct">
			<fd n="action">
				<V ty="string" v="type"></V>
			</fd>
			<fd n="parameters">
				<O ty="Array">
					<fd n="xpath">
						<V ty="xpath" v="//input[1][@id='retype']"></V>
					</fd>
					<fd n="id">
						<V ty="ID" v="retype"></V>
					</fd>
					<fd n="text">
						<V ty="string" v="FittestFittest"></V>
					</fd>
				</O>
			</fd>
		</O>
	</E>
	
</body>
