=== alebagnato/FITTEST/ITE-components/regression/SOAPMutation/xsd/WSDLConstraints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.fbk.eu/WSDLConstraints" xmlns:tns="http://www.fbk.eu/WSDLConstraints"
	elementFormDefault="qualified">
	<xs:element name="constraints">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="onElement" type="tns:onElementType"
					maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="author" type="xs:string" />
			<xs:attribute name="version" type="xs:string" />
			<xs:attribute name="createdDate" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="onElementType">
		<xs:choice>
			<xs:element name="restriction" type="tns:complexRestrictionType"></xs:element>
			<xs:element name="constraint" type="tns:constraintType"></xs:element>
		</xs:choice>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="xpath" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="constraintType">
		<xs:sequence>
			<xs:element name="expr" type="xs:string" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="lang" type="tns:constraintLanguage" />
	</xs:complexType>

	<xs:simpleType name="constraintLanguage">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OCL" />
			<xs:enumeration value="XCL" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="complexRestrictionType">
		<xs:sequence>
			<xs:group ref="tns:simpleRestrictionModel" />
		</xs:sequence>
		<xs:attribute name="base" type="xs:QName" use="required" />
	</xs:complexType>

	<xs:group name="simpleRestrictionModel">
		<xs:sequence>
			<xs:group ref="tns:facets" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<xs:group name="facets">
		<xs:choice>
			<xs:element ref="tns:minExclusive" />
			<xs:element ref="tns:minInclusive" />
			<xs:element ref="tns:maxExclusive" />
			<xs:element ref="tns:maxInclusive" />
			<xs:element ref="tns:totalDigits" />
			<xs:element ref="tns:fractionDigits" />
			<xs:element ref="tns:length" />
			<xs:element ref="tns:minLength" />
			<xs:element ref="tns:maxLength" />
			<xs:element ref="tns:enumeration" />
			<xs:element ref="tns:whiteSpace" />
			<xs:element ref="tns:pattern" />
		</xs:choice>
	</xs:group>

	<xs:element name="totalDigits" id="totalDigits">
		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="tns:numFacet">
					<xs:attribute name="value" type="xs:positiveInteger"
						use="required" />
				</xs:restriction>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="fractionDigits" id="fractionDigits" type="tns:numFacet">

	</xs:element>

	<xs:complexType name="facet">
		<xs:attribute name="value" use="required" />
	</xs:complexType>

	<xs:element name="minExclusive" id="minExclusive" type="tns:facet">

	</xs:element>
	<xs:element name="minInclusive" id="minInclusive" type="tns:facet">

	</xs:element>

	<xs:element name="maxExclusive" id="maxExclusive" type="tns:facet">

	</xs:element>
	<xs:element name="maxInclusive" id="maxInclusive" type="tns:facet">

	</xs:element>

	<xs:complexType name="numFacet">
		<xs:complexContent>
			<xs:restriction base="tns:facet">
				<xs:attribute name="value" type="xs:nonNegativeInteger"
					use="required" />
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="noFixedFacet">
		<xs:complexContent>
			<xs:restriction base="tns:facet">
				<xs:attribute name="fixed" use="prohibited" />
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>


	<xs:element name="length" id="length" type="tns:numFacet">

	</xs:element>
	<xs:element name="minLength" id="minLength" type="tns:numFacet">

	</xs:element>
	<xs:element name="maxLength" id="maxLength" type="tns:numFacet">

	</xs:element>

	<xs:element name="enumeration" id="enumeration" type="tns:noFixedFacet">

	</xs:element>

	<xs:element name="whiteSpace" id="whiteSpace">

		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="tns:facet">
					<xs:attribute name="value" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="preserve" />
								<xs:enumeration value="replace" />
								<xs:enumeration value="collapse" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:restriction>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="pattern" id="pattern">
		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="tns:noFixedFacet">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:restriction>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alebagnato/FITTEST/sub-projects/regression/SOAPMutation/xsd/EbayFindingAPIConstraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<constraints xmlns="http://www.fbk.eu/WSDLConstraints"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fbk.eu/WSDLConstraints WSDLConstraints.xsd ">
	<onElement xpath="//findItemsByKeywordsResponse/searchResult/item/itemId" name="title">
		<restriction base="string">
			<minLength value="5"/>
			<maxLength value="256"/>
		</restriction>
	</onElement>
	<onElement xpath="//findItemsByKeywordsResponse/searchResult/item/title" name="title">
		<restriction base="string">
			<whiteSpace value="collapse"/>
		</restriction>
	</onElement>
	<onElement xpath="//findItemsByKeywordsResponse/searchResult/item/globalId" name="globalId">
		<restriction base="string">
			<enumeration value="EBAY-AT"/>
			<enumeration value="EBAY-AU"/>
			<enumeration value="EBAY-CH"/>
			<enumeration value="EBAY-DE"/>
			<enumeration value="EBAY-ENCA"/>
			<enumeration value="EBAY-ES"/>
			<enumeration value="EBAY-FR"/>
			<enumeration value="EBAY-FRBE"/>
			<enumeration value="EBAY-FRCA"/>
			<enumeration value="EBAY-GB"/>
			<enumeration value="EBAY-HK"/>
			<enumeration value="EBAY-IE"/>
			<enumeration value="EBAY-IN"/>
			<enumeration value="EBAY-IT"/>
			<enumeration value="EBAY-MOTOR"/>
			<enumeration value="EBAY-MY"/>
			<enumeration value="EBAY-NL"/>
			<enumeration value="EBAY-NLBE"/>
			<enumeration value="EBAY-PH"/>
			<enumeration value="EBAY-PL"/>
			<enumeration value="EBAY-SG"/>
			<enumeration value="EBAY-US"/>
		</restriction>
	</onElement>
	<onElement xpath="//findItemsByKeywordsResponse/searchResult/item/condition/conditionId" name="conditionId">
		<restriction base="string">
			<enumeration value="Used"/>
			<enumeration value="New"/>
			<enumeration value="Unspecified"/>
		</restriction>
	</onElement>
	<onElement xpath="//searchResult/item/primaryCategory/categoryId" name="categoryId">
		<restriction base="integer">
			<maxInclusive value="99999"/>
			<minInclusive value="0"/>
		</restriction>
	</onElement>
	<onElement xpath="//searchResult/item/paymentMethod" name="paymentMethod">
		<restriction base="string">
			<enumeration value="AmEx"/>
			<enumeration value="CashInPerson"/>
			<enumeration value="CashOnPickup"/>
			<enumeration value="CCAccepted"/>
			<enumeration value="COD"/>
			<enumeration value="CODPrePayDelivery"/>
			<enumeration value="CustomCode"/>
			<enumeration value="Discover"/>
			<enumeration value="ELV"/>
			<enumeration value="Escrow"/>
			<enumeration value="LoanCheck"/>
			<enumeration value="MOCC"/>
			<enumeration value="Moneybookers"/>
			<enumeration value="MoneyXferAccepted"/>
			<enumeration value="MoneyXferAcceptedInCheckout"/>
			<enumeration value="None"/>
			<enumeration value="Other"/>
			<enumeration value="OtherOnlinePayments"/>
			<enumeration value="PaisaPayAccepted"/>
			<enumeration value="PaisaPayEscrowEMI"/>
			<enumeration value="Paymate"/>
			<enumeration value="PaymentSeeDescription"/>
			<enumeration value="PayPal"/>
			<enumeration value="PersonalCheck"/>
			<enumeration value="PostalTransfer"/>
			<enumeration value="PrePayDelivery"/>
			<enumeration value="ProPay"/>
			<enumeration value="VisaMC"/>
		</restriction>
	</onElement>
	<onElement xpath="//searchResult/item/sellingStatus/timeLeft" name="timeLeft">
		<restriction base="string">
			<pattern value="P[0-9]{2}DT[1-2]?[0-9]H[1-5]?[0-9]M[1-5]?[0-9]S"/>
		</restriction>
	</onElement>
	<onElement xpath="//searchResult/item/shippingInfo/shippingType" name="shippingType">
		<restriction base="string">
			<enumeration value="Calculated"/>
			<enumeration value="CalculatedDomesticFlatInternational"/>
			<enumeration value="Flat"/>
			<enumeration value="FlatDomesticCalculatedInternational"/>
			<enumeration value="Free"/>
			<enumeration value="FreePickup"/>
			<enumeration value="Freight"/>
			<enumeration value="FreightFlat"/>
			<enumeration value="NotSpecified"/>
		</restriction>
	</onElement>
</constraints>
