=== alebagnato/FITTEST/trunk/ITE Components standalone/transformtools/eu.fittest.fsm2cte/src/main/xsd/xinput.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.fbk.eu/xinput" xmlns:tns="http://www.fbk.eu/xinput"
	elementFormDefault="qualified">
	
	<xs:element name="domainInputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:xinput" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="tns:event" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="version" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="xinput">
		<xs:complexType>
			<xs:group ref="tns:inputSet" />	
			<xs:attributeGroup ref="tns:commonAttGroup"></xs:attributeGroup>
			<xs:attribute name="events" type="xs:IDREFS" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="event">
		<xs:complexType>
			<xs:attributeGroup ref="tns:commonAttGroup" />
			<xs:attribute name="reachedById" type="xs:string" />
			<xs:attribute name="reachedByName" type="xs:string" />
			<xs:attribute name="reachedByTagName" type="xs:string" />
			<xs:attribute name="reachedByLinkText" type="xs:string" />
			<xs:attribute name="reachedByPartialLinkText" type="xs:string" />
			<xs:attribute name="reachedByXPath" type="xs:string" />
			<xs:attribute name="reachedByURL" type="xs:string" />
			<xs:attribute name="reachedByCSS" type="xs:string" />
			<xs:attribute name="webType" type="tns:webElementType" use="optional" />
			<!-- 
			<xs:attribute name="webEventToFire" type="xs:string" use="required"/>
			changed to the following:
			 -->
			 <xs:attribute name="targetEventToFire" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="compositeParam">
		<xs:complexType>
			<xs:group ref="tns:inputSet" />
			<xs:attributeGroup ref="tns:commonAttGroup" />	
		</xs:complexType>
	</xs:element>

	<xs:group name="inputSet">
		<xs:sequence>
			<xs:element ref="tns:compositeParam" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="tns:compositeParamRef" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="tns:atomicParam" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="tns:atomicParamRef" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<xs:element name="compositeParamRef">
		<xs:complexType>
			<xs:attribute name="paramRef" type="xs:IDREF" use="required" />
			<xs:attribute name="name" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="atomicParamRef">
		<xs:complexType>
			<xs:attribute name="paramRef" type="xs:IDREF" use="required" />
			<xs:attribute name="name" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="atomicParam">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:dataClz" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attributeGroup ref="tns:commonAttGroup" />	
		</xs:complexType>
	</xs:element>
	
	<xs:element name="dataClz" type="tns:complexDataSpecType" />
	
	<xs:simpleType name="webElementType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="button" />
			<xs:enumeration value="textarea" />
			<xs:enumeration value="link" />
			<xs:enumeration value="select" />
			<xs:enumeration value="option" />
			<xs:enumeration value="label" />
			<xs:enumeration value="input" />
			<xs:enumeration value="fTextInput" />
			<xs:enumeration value="fButton" />
			<xs:enumeration value="fComboBox" />
			<xs:enumeration value="fCheckBox" />
			<xs:enumeration value="fDateField" />
			<xs:enumeration value="fDataGrid" />
			<xs:enumeration value="fRadioButton" />
			<xs:enumeration value="fTabNavigator" />
		</xs:restriction>
	</xs:simpleType>

	<xs:attributeGroup name="commonAttGroup">
		<xs:attribute name="id" type="xs:ID" />
		<xs:attribute name="name" type="xs:string" />
	</xs:attributeGroup>

	<xs:complexType name="complexDataSpecType">
		<xs:sequence>
			<xs:group ref="tns:simpleDataSpecType" />
		</xs:sequence>
		<xs:attribute name="base" type="xs:QName" use="required" />
		<xs:attributeGroup ref="tns:commonAttGroup"></xs:attributeGroup>
	</xs:complexType>

	<xs:group name="simpleDataSpecType">
		<xs:sequence>
			<xs:group ref="tns:facets" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:group>

	<xs:group name="facets">
		<xs:choice>
			<xs:element ref="tns:minExclusive" />
			<xs:element ref="tns:minInclusive" />
			<xs:element ref="tns:maxExclusive" />
			<xs:element ref="tns:maxInclusive" />
			<xs:element ref="tns:totalDigits" />
			<xs:element ref="tns:fractionDigits" />
			<xs:element ref="tns:length" />
			<xs:element ref="tns:minLength" />
			<xs:element ref="tns:maxLength" />
			<xs:element ref="tns:enumeration" />
			<xs:element ref="tns:pattern" />
		</xs:choice>
	</xs:group>

	<xs:element name="totalDigits" id="totalDigits">
		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="tns:numFacet">
					<xs:attribute name="value" type="xs:positiveInteger"
						use="required" />
				</xs:restriction>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="fractionDigits" id="fractionDigits" type="tns:numFacet">

	</xs:element>

	<xs:complexType name="facet">
		<xs:attribute name="value" use="required" />
	</xs:complexType>

	<xs:element name="minExclusive" id="minExclusive" type="tns:facet">

	</xs:element>
	<xs:element name="minInclusive" id="minInclusive" type="tns:facet">

	</xs:element>

	<xs:element name="maxExclusive" id="maxExclusive" type="tns:facet">

	</xs:element>
	<xs:element name="maxInclusive" id="maxInclusive" type="tns:facet">

	</xs:element>

	<xs:complexType name="numFacet">
		<xs:complexContent>
			<xs:restriction base="tns:facet">
				<xs:attribute name="value" type="xs:nonNegativeInteger"
					use="required" />
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="noFixedFacet">
		<xs:complexContent>
			<xs:restriction base="tns:facet">
				<xs:attribute name="fixed" use="prohibited" />
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>


	<xs:element name="length" id="length" type="tns:numFacet">

	</xs:element>
	<xs:element name="minLength" id="minLength" type="tns:numFacet">

	</xs:element>
	<xs:element name="maxLength" id="maxLength" type="tns:numFacet">

	</xs:element>

	<xs:element name="enumeration" id="enumeration" type="tns:noFixedFacet">

	</xs:element>

	<xs:element name="pattern" id="pattern">
		<xs:complexType>
			<xs:complexContent>
				<xs:restriction base="tns:noFixedFacet">
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:restriction>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alebagnato/FITTEST/trunk/ITE Release/eu.fittest.fbk/eu.fittest.eventSequenceGenerator/input/NotePadTest/model/NotePad.xml
<?xml version="1.0" encoding="UTF-8"?>
<domainInputs name="NotePad" version="0.2"
	xmlns="http://www.fbk.eu/xinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fbk.eu/xinput http://selab.fbk.eu/dnguyen/xsd/xinput.xsd ">

	<xinput events="select_note_0" id="note_input">
		<atomicParam id="note_list">
			<dataClz base="int">
				<enumeration value="0" />
				<enumeration value="1" />
			</dataClz>
		</atomicParam>
	</xinput>

	<xinput events="type_Keys_0" id="string_input">
		<atomicParam id="input_string">
			<dataClz base="string" name="good">
				<pattern value="[a-z0-9]+" />
			</dataClz>
			<dataClz base="string" name="bad">
				<pattern value="[#$%]{4,6}" />
			</dataClz>
		</atomicParam>
	</xinput>
	
	<event id="click_Add_note" reachedByName="&quot;Add note&quot;" targetEventToFire="clickOnMenuItem" />
	<event id="click_Delete" reachedByName="&quot;Delete&quot;" targetEventToFire="clickOnMenuItem" />
	<event id="click_Discard" reachedByName="&quot;Discard&quot;" targetEventToFire="clickOnMenuItem" />
	<event id="click_Edit_title" reachedByName="&quot;Edit title&quot;" targetEventToFire="clickOnMenuItem" />
	<event id="click_Revert_changes" reachedByName="&quot;Revert changes&quot;" targetEventToFire="clickOnMenuItem" />
	<event id="click_Save" reachedByName="&quot;Save&quot;" targetEventToFire="clickOnMenuItem" />
	
	<event id="click_OK" reachedById="0" targetEventToFire="clickOnButton" />
	<event id="click_back" reachedById="0" targetEventToFire="goBack()"/>
	<event id="select_note_0" reachedById="0" targetEventToFire="clickInList(0)" />
	<event id="type_Keys_0" reachedById="0" targetEventToFire="enterText" />
	
	<event id="long_click_note_0" reachedById="0" targetEventToFire="clickLongOnText(&quot;Note1&quot;)" />
	<event id="click_onText_Open" reachedById="0" targetEventToFire="clickOnText(&quot;Open&quot;)" />
	<event id="click_onText_Delete" reachedById="1" targetEventToFire="clickOnText(&quot;Delete&quot;)"/>
	<event id="click_onText_Edit_title" reachedById="2" targetEventToFire="clickOnText(&quot;Edit title&quot;)"/>
	
</domainInputs>

=== alebagnato/FITTEST/ITE Release/eu.fittest.fsm2cte/src/test/data/selben.xml
<?xml version="1.0" encoding="UTF-8"?>
<domainInputs name="selben" version="0.1"
	xmlns="http://www.fbk.eu/xinput" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fbk.eu/xinput ../xsd/xinput.xsd ">

	<xinput id="num_factor_input" events="num_enterText factor_enterText">
		<atomicParam id="number">
			<dataClz base="int" name="big">
				<minInclusive value="1000" />
			</dataClz>
			<dataClz base="int" name="small">
				<minInclusive value="0" />
				<maxExclusive value="100" />
			</dataClz>
			<dataClz base="int" name="medium">
				<minInclusive value="100" />
				<maxExclusive value="1000" />
			</dataClz>
		</atomicParam>
	</xinput>
	
	<xinput id="fruits_input" events="combo_selectComboItem">
		<atomicParam id="fruits">
			<dataClz base="string" name="fruit">
				<enumeration value="apple"/>
				<enumeration value="banana"/>
				<enumeration value="grape"/>
			</dataClz>
		</atomicParam>
	</xinput>
	
	<xinput id="date_input" events="date_enterDate">
		<atomicParam id="date">
			<dataClz base="date" name="date" />
		</atomicParam>
	</xinput>
	
	<xinput id="tabs_input" events="tabs_selectTab">
		<atomicParam id="tabs">
			<dataClz base="string" name="tabs">
				<enumeration value="Fruit"/>
				<enumeration value="Veg"/>
				<enumeration value="Cheese"/>
			</dataClz>
		</atomicParam>
	</xinput>
	
	<xinput id="checkbox_input" events="checkBox_setCheckBoxState">
		<atomicParam id="checkvalue">
			<dataClz base="string" name="checkvalue">
				<enumeration value="true"/>
				<enumeration value="false"/>
			</dataClz>
		</atomicParam>
	</xinput>
	
	<event id="num_enterText" webType="fTextInput" webEventToFire="enterText" reachedBy="num" />
	<event id="factor_enterText" webType="fTextInput" webEventToFire="enterText" reachedBy="factor"/>
	<event id="combo_selectComboItem" webType="fComboBox" webEventToFire="selectComboItem" reachedBy="combo"/>

	<event id="checkBox_setCheckBoxState" webType="fCheckBox" webEventToFire="setCheckBoxState" reachedBy="checkBox"/>
	<event id="date_enterDate" webType="fDateField" webEventToFire="enterDate" reachedBy="date"/>
	<event id="tabs_selectTab" webType="fTabNavigator" webEventToFire="selectTab" reachedBy="tabs" />

	<event id="button_clickButton" webType="fButton" reachedBy="button"/>
	<event id="Pick_clickButton" webType="fButton" reachedBy="Pick"/>
	<event id="Cox_clickButton" webType="fButton" reachedBy="Cox"/>

</domainInputs>

=== alebagnato/FITTEST/trunk/ITE/eu.fittest.fsm2cte/src/test/data/xinput.xml
<?xml version="1.0" encoding="UTF-8"?>
<domainInputs name="shoppingCart" version="0.1" xmlns="http://www.fbk.eu/xinput"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.fbk.eu/xinput ../xsd/xinput.xsd ">
	
	<xinput id="add_input" events="add">
		<atomicParam id="itemid" name="itemid">
			<dataClz base="string" name="itemid">
				<enumeration value="hat001"/>
				<enumeration value="dog001"/>
				<enumeration value="sou001"/>
				<enumeration value="cha001"/>
				<enumeration value="str001"/>
				<enumeration value="qua001"/>
			</dataClz> 
		</atomicParam>
	</xinput>
	
	<xinput id="remove_input" events="rem">
		<atomicParamRef paramRef="itemid" />
	</xinput>

	<xinput id="add_remove" events="add rem">
		<atomicParamRef paramRef="itemid" />
	</xinput>
	
	<xinput id="empty_input" events="empty"/>
	
	<xinput id="book_input" events="none">
		<compositeParam id="bookdata">
			<atomicParam id="title">
				<dataClz base="string" name="fulltitle">
					<minLength value="3"/>
					<maxLength value="1024"/>
				</dataClz>
			</atomicParam>
			<atomicParam id="price"> 
				<dataClz base="double" name="expensive">
					<minInclusive value="10.0"/>
				</dataClz>
				<dataClz base="double" name="cheap">
					<minInclusive value="0.0"/>
					<maxExclusive value="10.0"/>
				</dataClz>
			</atomicParam>
			<atomicParam id="date"> 
				<dataClz base="string" name="date">
					<pattern value="^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$"/>
				</dataClz>
			</atomicParam>
		</compositeParam>
		<atomicParamRef paramRef="itemid" />
	</xinput>
	
	<event id="add" name="add" webType="button" webEventToFire="onclick" reachedBy="//button[@id='btnAdd']"/>
	<event id="rem" name="remove" webType="button" webEventToFire="onclick" reachedBy="//button[@id='btnRemove']"/>
	<event id="empty" name="empty" webType="button" webEventToFire="onclick" reachedBy="//button[@id='btnEmpty']"/>
	
</domainInputs>
